"""add interview completion

Revision ID: 6b8bb8aeee76
Revises: 3ebb9312bc42
Create Date: 2026-02-01 21:01:13.170627
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6b8bb8aeee76'
down_revision = '3ebb9312bc42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('is_completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'is_completed')
    # ### end Alembic commands ###
